{%set name = "Flask-CouchDB" %}
{%set version = "0.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: a753758dc172bca3c35e2f093f15c22c735ee3291b19fd549d0e8abb329856eb

build:
  number: 1
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  build:
    - python
    - pip
  run:
    - python
    - flask
    - python-couchdb >=0.7

test:
  imports:
    - flaskext
    - flaskext.couchdb

about:
  home: http://bitbucket.org/leafstorm/flask-couchdb/
  license: MIT
  license_file: LICENSE
  license_family: MIT
  summary: 'Provides utilities for using CouchDB with Flask'
  dev_url: http://bitbucket.org/leafstorm/flask-couchdb/
  doc_url: https://pythonhosted.org/Flask-CouchDB/

extra:
  recipe-maintainers:
    - pmlandwehr
