# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    
    - CONDA_PY=27
    - CONDA_PY=35
    - CONDA_PY=36
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "XD+3zO+8cjeji5t6ZlO44VDxgnrTkJGzaBMaUZdXBD5u6Fc4iyUlpicsc83iNPci7/FcgkNEKRzuiCq+OLuk0o81dRr5lxv20z8t0L4q+GzGjqsWCoBA7pZ7peXWOfR9+KWNmrja3+fxAOW6rDevzLx7npyEb8bX38AEMbnS7drvRX8dFwd0OKkMjZxbGKQzm2CelD/lVdStywYmHrtxN/KkAreloxLwSsv1dsfHhCdsXxSBxw7r08qEiCWDhnU60wtU/Q9RbwrLyh2Uap2dKOpRiemKa/VL4l0Eq1wlZv7MofzBio+7/HH2yTb2loIcK/LsewgdWuTpQeXCwL3Sgwj8IYIjCAGxR1NaLOMFw++bkFsJ+MqtDtZk2nrY/Dg7+yF2vfocpYkLKGth3ziSHaUvY9gS2pJuex3P5KTmJTOzG90DKMRCMj73skjc0g2q5O0XuyAKdQGkDjTnXumvcqMekf6RJzjkdvQ6nidxSVfppE0PT10fnCAdkKC0iSi8Y9E81pgW4O86S1ebfA4Q6X65ulnUkRO8ewl2OZkR/LjtyRc1R0wKXcSE6X+9sUVlbXP4wr5PpkhYdLb/kOlW1W9r4QHvO1nPdahJJ7WrtJNMmXC9A3TbaA9/thCYoiMxaDtXUzJf+3okCQYVmh/mqy2if26jwi+p5mjfN4Gb8DY="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
