travis:
  secure:
    BINSTAR_TOKEN: r1iOPpH32Gwofrj3VN+CXn0NgNSPeWCTS+7mFUPyV8slN1ECYlsc64YAIwFgtM4fLEnvlM5zwgr2HtC9FsMeEc8RVApfzJxFu/91KHbSRlbxYC4OnhfoddhuEDvZKN0v6Bi5PSIrqSk7lc+ePzZeGKNEVu2hKV7S53NqzCTUlbt/hh1wC2Rlr1J0+LnXslQg+VkX0y+3c4XTkCe7yBLV0LxumUBGMwW2BxMBieD475Yqxn5ezydfQYDouWD6IrtOa+w61S6YJu2gL4IILmuLxJ/gbza4jXdtuKpBDKYfGg5Dw04yt/DU3CwiO07hcGJefgbwxV1/5aJGgD8ST5mFF6i0ewws6tEh5E5T8wV2GOfNhe7Wt493BRlCYGmB6/7naiASneDnUNobbw4tW9549OU3XqAgZeLKtJntF1KNfrEAu5PuUKdgIduvEOIzn8IFgGt8SRc0ch528bf8DXW0xVdeQ1aQGz1IaA6xMS2li+onRKbbRNzvP21atlZzu/AVKQVFRudGsuftfDiEgsZ19lmOq5kgn7c3YDZAyg6b340UeRVzW4u3of7aB95ws5onoBiB1pXe8ig7Gjr/1PjaoQHRo3zmGVRuw3HHV7tBujvNl1iofM7b9EiGpJZevlxbQblCdwA9A3esJW4cZTgPxHe0EPEBjqGYB2HJKbxy8so=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
