appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: XD+3zO+8cjeji5t6ZlO44VDxgnrTkJGzaBMaUZdXBD5u6Fc4iyUlpicsc83iNPci7/FcgkNEKRzuiCq+OLuk0o81dRr5lxv20z8t0L4q+GzGjqsWCoBA7pZ7peXWOfR9+KWNmrja3+fxAOW6rDevzLx7npyEb8bX38AEMbnS7drvRX8dFwd0OKkMjZxbGKQzm2CelD/lVdStywYmHrtxN/KkAreloxLwSsv1dsfHhCdsXxSBxw7r08qEiCWDhnU60wtU/Q9RbwrLyh2Uap2dKOpRiemKa/VL4l0Eq1wlZv7MofzBio+7/HH2yTb2loIcK/LsewgdWuTpQeXCwL3Sgwj8IYIjCAGxR1NaLOMFw++bkFsJ+MqtDtZk2nrY/Dg7+yF2vfocpYkLKGth3ziSHaUvY9gS2pJuex3P5KTmJTOzG90DKMRCMj73skjc0g2q5O0XuyAKdQGkDjTnXumvcqMekf6RJzjkdvQ6nidxSVfppE0PT10fnCAdkKC0iSi8Y9E81pgW4O86S1ebfA4Q6X65ulnUkRO8ewl2OZkR/LjtyRc1R0wKXcSE6X+9sUVlbXP4wr5PpkhYdLb/kOlW1W9r4QHvO1nPdahJJ7WrtJNMmXC9A3TbaA9/thCYoiMxaDtXUzJf+3okCQYVmh/mqy2if26jwi+p5mjfN4Gb8DY=}
conda_forge_output_validation: true
